from pyAudioAnalysis import audioTrainTest as aT
classes = [
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Airplane',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Breathing',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Brushingteeth',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Canopening',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Carhorn',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Cat',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Chainsaw',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Chirpingbirds',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Churchbells',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Clapping',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Clockalarm',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Clocktick',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Coughing',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Cow',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Cracklingfire',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Crickets',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Crow',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Cryingbaby',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Dog',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Door',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Doorknock',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Drinking',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Engine',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Fireworks',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Footsteps',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Frog',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Glassbreaking',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Handsaw',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Helicopter',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Hen',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Insects',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Keyboardtyping',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Laughing',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Mouseclick',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Pig',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Pouringwater',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Rain',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Rooster',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Seawaves',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Sheep',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Siren',
'/Users/chiragmandot/AtntHackathon/data/fulldata/Sneezing',
'/Users/chiragmandot/AtntHackathon/data/fulldata/NotSneezing',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Snoring',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Thunderstorm',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Toiletflush',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Train',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Vacuumcleaner',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Washingmachine',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Waterdrops',
#'/Users/chiragmandot/AtntHackathon/data/fulldata/Wind'
]

aT.featureAndTrain(classes, 1.0, 1.0, aT.shortTermWindow, aT.shortTermStep, "gradientboosting", "GBoostSneezer", False)
aT.featureAndTrain(classes, 1.0, 1.0, aT.shortTermWindow, aT.shortTermStep, "randomforest", "RFSneezer", False)

